// src/components/app/Header.tsx
import React from 'react';

interface HeaderProps {
  title: string;
  appStateLabel: string;
  appStateValue: string;
}

export const Header: React.FC<HeaderProps> = ({ title, appStateLabel, appStateValue }) => {
  return (
    <header className="flex flex-col items-center text-center">
      <h1 className="text-xl font-bold">{title}</h1>
      <p className="text-lg">
        {appStateLabel}: <code className="font-mono bg-gray-200 dark:bg-gray-800 p-1 rounded">{appStateValue}</code>
      </p>
    </header>
  );
};

// src/components/app/Header.svelte
<script lang="ts">
  interface Props {
    title: string;
    appStateLabel: string;
    appStateValue: string;
  }

  const { title, appStateLabel, appStateValue }: Props = $props();
</script>

<header class="header">
  <h1 class="title">{title}</h1>
  <div class="debug">
    <span class="label">{appStateLabel}:</span>
    <code class="value">{appStateValue}</code>
  </div>
</header>

<style>
  .header {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--spacing-2);
    width: 100%;
    padding: var(--spacing-4) 0;
  }

  .title {
    font-size: 1.5rem;
    font-weight: 700;
    color: var(--color-text-primary);
  }

  .debug {
    font-size: 0.75rem;
    color: var(--color-text-muted);
    font-family: var(--font-mono);
  }

  .label {
    margin-right: var(--spacing-1);
  }

  .value {
    background-color: var(--color-surface);
    padding: var(--spacing-1) var(--spacing-2);
    border-radius: var(--radius-sm);
  }
</style>
