// src/components/app/MainContent.svelte
<script lang="ts">
  import type { Actor, StateFrom } from 'xstate';
  import type { appMachine, AppEvent } from '$machines/app.machine';
  import type { trainingMachine } from '$machines/training.machine';
  import type { Dictionary } from '$interfaces/types';
  import { fingerLayoutASDF } from '$data/layouts/finger-layout-asdf';
  import { keyboardLayoutANSI } from '$data/layouts/keyboard-layout-ansi';

  import TrainingScene from '$components/ui/TrainingScene.svelte';
  import LessonStatsDisplay from '$components/ui/LessonStatsDisplay.svelte';
  import UserPreferencesPage from '$components/ui/UserPreferencesPage.svelte';

  interface Props {
    state: StateFrom<typeof appMachine>;
    send: (event: AppEvent) => void;
    dictionary: Dictionary;
    trainingActor: Actor<typeof trainingMachine> | undefined;
  }

  const { state, send, dictionary, trainingActor }: Props = $props();
</script>

{#if state.matches({ training: 'running' }) && trainingActor}
  <TrainingScene {trainingActor} fingerLayout={fingerLayoutASDF} keyboardLayout={keyboardLayoutANSI} {dictionary} />
{:else if state.matches('trainingComplete') && state.context.lastTrainingStream}
  <LessonStatsDisplay stream={state.context.lastTrainingStream} {dictionary} />
{:else if state.matches('settings')}
  <UserPreferencesPage onBack={() => send({ type: 'TO_MENU' })} {dictionary} />
{:else if state.matches('allStat')}
  <h2 class="screen-title">{dictionary.app.stats_screen_title}</h2>
{:else if state.matches({ training: 'paused' })}
  <h2 class="screen-title pause">{dictionary.app.pause}</h2>
{:else if state.matches('error')}
  <h2 class="screen-title error">{dictionary.app.error_title}</h2>
{:else if state.matches('initializing')}
  <div class="loading">{dictionary.app.loading}</div>
{:else}
  <div class="welcome">
    <p>{dictionary.app.welcome}</p>
  </div>
{/if}

<style>
  .screen-title {
    font-size: 1.5rem;
    font-weight: 700;
  }

  .pause {
    color: var(--color-text-secondary);
  }

  .error {
    color: var(--color-error);
  }

  .loading {
    color: var(--color-text-muted);
  }

  .welcome {
    padding: var(--spacing-4);
    text-align: center;
    color: var(--color-text-secondary);
  }
</style>

// src/components/app/MainContent.tsx
import React from 'react';
import { type Actor, type StateFrom } from 'xstate';
import { type appMachine, type AppEvent } from '@/machines/app.machine';
import { type trainingMachine } from '@/machines/training.machine';
import { Dictionary } from '@/interfaces/types';

import { TrainingScene } from "@/components/ui/training-scene";
import { LessonStatsDisplay } from "@/components/ui/lesson-stats-display";
import { UserPreferencesPage } from "@/components/ui/user-preferences-page";
import { fingerLayoutASDF } from "@/data/layouts/finger-layout-asdf";
import { keyboardLayoutANSI } from "@/data/layouts/keyboard-layout-ansi";

interface MainContentProps {
  state: StateFrom<typeof appMachine>;
  send: (event: AppEvent) => void;
  dictionary: Dictionary;
  trainingActor: Actor<typeof trainingMachine> | undefined;
}

export const MainContent: React.FC<MainContentProps> = ({ state, send, dictionary, trainingActor }) => {
  if (state.matches({ training: 'running' }) && trainingActor) {
    return <TrainingScene trainingActor={trainingActor} fingerLayout={fingerLayoutASDF} keyboardLayout={keyboardLayoutANSI} dictionary={dictionary} />;
  }
  if (state.matches('trainingComplete')) {
      return <LessonStatsDisplay stream={state.context.lastTrainingStream!} dictionary={dictionary} />;
  }
  if (state.matches('settings')) {
      return <UserPreferencesPage onBack={() => send({ type: 'TO_MENU' })} dictionary={dictionary} />;
  }
  if (state.matches('allStat')) {
      return <h2>{dictionary.app.stats_screen_title}</h2>;
  }
  if (state.matches({ training: 'paused' })) {
      return <h2 className="text-2xl font-bold">{dictionary.app.pause}</h2>;
  }
  if (state.matches('error')) {
      return <h2 className="text-red-500">{dictionary.app.error_title}</h2>;
  }
  if (state.matches('initializing')) {
      return <div>{dictionary.app.loading}</div>;
  }
  // Default content for 'menu'
  return <div className="p-4 text-center"><p>{dictionary.app.welcome}</p></div>;
};
