// src/components/ui/button.tsx
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/lib/utils"

export const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
  {
    variants: {
      variant: {
        default:
          "bg-primary text-primary-foreground shadow-xs hover:bg-primary/90",
        destructive:
          "bg-destructive text-white shadow-xs hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
        outline:
          "border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50",
        secondary:
          "bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80",
        ghost:
          "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2 has-[>svg]:px-3",
        sm: "h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5",
        lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
        icon: "size-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export type ButtonProps =  React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }

export function Button({
  className,
  variant,
  size,
  asChild = false,
  ...props
}: ButtonProps) {
  const Comp = asChild ? Slot : "button"

  return (
    <Comp
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

// src/components/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  interface ButtonProps extends Omit<HTMLButtonAttributes, 'type' | 'disabled' | 'class'> {
    variant?: 'neutral' | 'primary' | 'success' | 'danger' | 'ghost' | 'accent';
    size?: 'md' | 'lg';
    href?: string;
    type?: 'button' | 'submit';
    disabled?: boolean;
    children: Snippet;
  }

  const {
    variant = 'neutral',
    size = 'md',
    href,
    type = 'button',
    disabled = false,
    children,
    ...rest
  }: ButtonProps = $props();
</script>

<svelte:element
  this={href ? 'a' : 'button'}
  {...rest}
  class="button {variant} {size}"
  href={href || undefined}
  type={href ? undefined : type}
  disabled={href ? undefined : disabled}
>
  {@render children()}
</svelte:element>

<style>
  .button {
    display: inline-flex;
    align-items: center;
    gap: var(--spacing-2);
    border-radius: var(--radius-3);
    border: 1px solid transparent;
    font-family: var(--font-sans);
    cursor: pointer;
    text-decoration: none;
  }

  .button:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  /* --- sizes --- */
  .md {
    padding: var(--spacing-2) var(--spacing-4);
    font-size: var(--font-size-sm);
    font-weight: var(--font-weight-medium);
  }
  .lg {
    padding: var(--spacing-3) var(--spacing-6);
    font-size: var(--font-size-md);
    font-weight: var(--font-weight-semibold);
  }

  /* --- variants --- */
  .neutral {
    background: var(--color-surface);
    color: var(--color-text-primary);
    border-color: var(--color-border);
  }
  .neutral:hover:not(:disabled) {
    background: var(--color-surface-hover);
  }

  .primary {
    background: var(--color-primary-background);
    color: var(--color-on-dense);
    border-color: var(--color-primary-background);
  }
  .primary:hover:not(:disabled) {
    background: var(--color-primary-hover);
    border-color: var(--color-primary-hover);
  }

  .success {
    background: var(--color-success);
    color: var(--color-on-dense);
    border-color: var(--color-success);
  }
  .success:hover:not(:disabled) {
    background: var(--color-success-hover);
    border-color: var(--color-success-hover);
  }

  .danger {
    background: var(--color-error);
    color: var(--color-on-dense);
    border-color: var(--color-error);
  }
  .danger:hover:not(:disabled) {
    background: var(--color-error-hover);
    border-color: var(--color-error-hover);
  }

  .ghost {
    background: transparent;
    color: var(--color-text-primary);
    border-color: var(--color-text-secondary);
  }
  .ghost:hover:not(:disabled) {
    border-color: var(--color-text-primary);
  }

  .accent {
    background: var(--color-brand-accent);
    color: var(--color-cursor-foreground);
    border-color: transparent;
  }
  .accent:hover:not(:disabled) {
    background: var(--color-brand-accent-hover);
  }
  .accent:active:not(:disabled) {
    transform: translateY(1px);
  }

  /* --- focus --- */
  .button:focus-visible {
    outline: var(--focus-ring-width) solid var(--color-text-primary);
    outline-offset: var(--focus-ring-offset);
  }
  .accent:focus-visible {
    outline: var(--focus-ring-width) solid var(--color-brand-accent);
    outline-offset: 3px;
  }

  /* --- KeyHint нейтрализация на плотных/accent --- */
  .primary :global(.key-hint),
  .success :global(.key-hint),
  .danger :global(.key-hint),
  .accent :global(.key-hint) {
    background: transparent;
    border-color: currentColor;
    color: inherit;
    opacity: 0.85;
  }
</style>
