// src/components/flow-line/FlowLine.svelte
<script lang="ts">
  import RegularSymbol from './RegularSymbol.svelte';
  import CursorSymbol from './CursorSymbol.svelte';
  import type { EnrichedStreamSymbol } from '@/lib/stream-utils';
  import type {
    KeyCapPressResult,
    FlowLineCursorType,
    FlowLineCursorMode,
  } from '@/interfaces/types';

  interface Props {
    symbols: EnrichedStreamSymbol[];
    cursorPosition: number;
    pressResult?: KeyCapPressResult;
    cursorType?: FlowLineCursorType;
    cursorMode?: FlowLineCursorMode;
    blink?: boolean;
  }

  const {
    symbols,
    cursorPosition,
    pressResult = 'NONE',
    cursorType,
    cursorMode = 'HALF',
    blink = true,
  }: Props = $props();

  const completedCount = 100;
  const pendingCount = 100;

  const startCompleted = $derived(Math.max(0, cursorPosition - completedCount));
  const completedSymbols = $derived(symbols.slice(startCompleted, cursorPosition));
  // undefined для пустого потока или cursorPosition >= symbols.length — guard в JSX ниже.
  const cursorSymbol = $derived(symbols[cursorPosition]);
  const endPending = $derived(cursorPosition + 1 + pendingCount);
  const pendingSymbols = $derived(symbols.slice(cursorPosition + 1, endPending));
</script>

<div class="flow-line {cursorMode} {pressResult}">
  <div class="completed-symbols">
    {#each completedSymbols as symbol, i (startCompleted + i)}
      <RegularSymbol symbol={symbol.char} symbolType={symbol.type} />
    {/each}
  </div>

  <CursorSymbol {cursorType} {blink} symbol={cursorSymbol?.char ?? ''} />

  <div class="pending-symbols">
    {#each pendingSymbols as symbol, i (cursorPosition + 1 + i)}
      <RegularSymbol symbol={symbol.char} />
    {/each}
  </div>
</div>

<style>
  .flow-line {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100vw;
    font-family: var(--font-mono);
    font-size: 1.875rem;
    border: var(--flow-line-border);
  }

  .completed-symbols {
    display: flex;
    justify-content: flex-end;
    white-space: nowrap;
    text-align: right;
    overflow: hidden;
  }

  .pending-symbols {
    display: flex;
    justify-content: flex-start;
    white-space: pre;
    text-align: left;
    overflow: hidden;
  }

  /* Cursor mode variants */
  .HALF .completed-symbols { width: 50%; }
  .HALF .pending-symbols { width: 50%; }
  .THIRD .completed-symbols { width: 33.333%; }
  .THIRD .pending-symbols { width: 66.666%; }
  .QUARTER .completed-symbols { width: 25%; }
  .QUARTER .pending-symbols { width: 75%; }
  .DINAMIC .completed-symbols { min-width: 8.333%; }
  .DINAMIC .pending-symbols { min-width: 50%; }

  /* Press result variants */
  .NONE { background: transparent; }
  .CORRECT { background: var(--flow-line-correct-background); }
  .ERROR { background: var(--flow-line-error-background); }
</style>

// src/components/ui/flow-line.tsx
/**
 * @file Компонент `FlowLine` для визуализации потока ввода текста.
 * @description Имитирует движение каретки печатной машинки, разделяя текст
 * на набранную часть, текущий символ (курсор) и оставшуюся часть.
 * Динамически отображает состояние символов (правильно/неправильно набрано).
 */
import { cva, VariantProps } from "class-variance-authority";

import { FlowLineCursorMode, FlowLineCursorType, FlowLineSize, KeyCapPressResult, TypingStream } from '@/interfaces/types';
import { getSymbolChar, getSymbolType } from '@/lib/stream-utils';
import { cn } from '@/lib/utils';
import { CursorSymbol } from "./cursor-symbol";
import { RegularSymbol } from "./regular-symbol";

// --- Variants ---

/**
 * Варианты стилей для `FlowLine` на основе CVA.
 * Определяет размер шрифта и режим отображения курсора.
 */
const flowLineVariants = cva(
  "w-screen flex justify-center items-center font-mono border-2 border-amber-400",
  {
    variants: {
      /** Размер шрифта для символов в строке. */
      size: {
        XS: "text-xl",
        SM: "text-2xl",
        MD: "text-3xl",
        LG: "text-4xl",
        XL: "text-5xl",
      } satisfies Record<FlowLineSize, string>,
      /** Режим отображения курсора, влияющий на соотношение ширины зон. */
      cursorMode: {
        HALF: "[&_.completed-symbols]:w-1/2            [&_.pending-symbols]:w-1/2",
        THIRD: "[&_.completed-symbols]:w-1/3           [&_.pending-symbols]:w-2/3",
        QUARTER: "[&_.completed-symbols]:w-1/4         [&_.pending-symbols]:w-3/4",
        DINAMIC: "[&_.completed-symbols]:min-w-1/12    [&_.pending-symbols]:min-w-1/2",
      } satisfies Record<FlowLineCursorMode, string>,
      /** Результат нажатия клавиши. */
      pressResult: {
        NONE: "",
        CORRECT: "bg-green-100",
        ERROR: "bg-red-100",
      } satisfies Record<KeyCapPressResult, string>,
    },
    defaultVariants: {
      size: "MD",
      cursorMode: "HALF",
    },
  }
);

// --- Main Component ---

/** Пропсы для компонента `FlowLine`. */
export interface FlowLineProps extends VariantProps<typeof flowLineVariants> {
  /** Поток символов для отображения. */
  stream: TypingStream;
  /** Текущая позиция курсора в потоке символов. */
  cursorPosition: number;
  /** Тип визуализации курсора. */
  cursorType?: FlowLineCursorType;
  /** Дополнительные классы CSS. */
  className?: string;
}

/**
 * Компонент `FlowLine` визуализирует процесс набора текста,
 * отображая пройденные символы, текущий символ под курсором и ожидающие символы.
 * @param props Пропсы компонента.
 * @returns Элемент JSX, представляющий строку потока ввода.
 */
export function FlowLine({ stream, cursorPosition, cursorType, cursorMode, size, pressResult, className }: FlowLineProps) {
  const completedCount = 100; // Количество отображаемых пройденных символов
  const pendingCount = 100;    // Количество отображаемых ожидающих символов

  const startCompleted = Math.max(0, cursorPosition - completedCount);
  const completedSymbolsToRender = stream.slice(startCompleted, cursorPosition);

  const cursorSymbol = stream[cursorPosition];

  const endPending = cursorPosition + 1 + pendingCount;
  const pendingSymbolsToRender = stream.slice(cursorPosition + 1, endPending);

  return (
    <div className={cn(flowLineVariants({ cursorMode, size, pressResult, className }))}>

      {/* ---- Completed Symbols ---- */}
      <div className="completed-symbols flex justify-end whitespace-nowrap text-right overflow-hidden">
        {completedSymbolsToRender.map((symbol, index) => (
          <RegularSymbol
            key={startCompleted + index}
            symbol={getSymbolChar(symbol)}
            symbolType={getSymbolType(symbol)}
          />
        ))}
      </div>

      {/* ---- Cursor Symbol ---- */}
      <CursorSymbol
        key={cursorPosition}
        cursorType={cursorType}
        symbol={cursorSymbol ? getSymbolChar(cursorSymbol) : ''}
      />

      {/* ---- Pending Symbols ---- */}
      <div className="pending-symbols flex justify-start whitespace-pre text-left overflow-hidden">
        {pendingSymbolsToRender.map((symbol, index) => (
          <RegularSymbol
            key={cursorPosition + 1 + index}
            symbol={getSymbolChar(symbol)}
          />
        ))}
      </div>
    </div>
  );
}
