// src/components/ui/flow-line.tsx
import { cn } from '@/lib/utils';
import { FlowLineCursorType, FlowLineSymbolType, TypingStream } from '@/interfaces/types';
import { useState, useEffect } from 'react';
import { cva, VariantProps } from "class-variance-authority";
import { getSymbolType, getSymbolChar } from '@/lib/flow-line-utils';

// --- Main Component ---

export interface FlowLineProps {
  stream: TypingStream;
  cursorPosition: number;
  cursorType?: FlowLineCursorType;
  className?: string;
}

export function FlowLine({ stream, cursorPosition, cursorType, className }: FlowLineProps) {
  const completedSymbols = stream.slice(0, cursorPosition);
  const cursorSymbol = stream[cursorPosition];
  const pendingSymbols = stream.slice(cursorPosition + 1);
  const completedCount = -100;
  const pendingCount = 100;

  return (
    <div className={cn(`w-screen flex justify-center items-center  
     font-mono text-4xl`, className)}>

      {/* ---- Completed Symbols ---- */}
      <span className="flex justify-end whitespace-nowrap text-right overflow-hidden min-w-1/3 bg-amber-100">
        {completedSymbols.slice(completedCount).map((symbol, index) => (
          <RegularSymbol
            key={index}
            symbol={getSymbolChar(symbol)}
            symbolType={getSymbolType(symbol)}
          />
        ))}
      </span>

      {/* ---- Cursor Symbol ---- */}
      <CursorSymbol
        key={cursorPosition}
        cursorType={cursorType}
        symbol={cursorSymbol ? getSymbolChar(cursorSymbol) : ''}
      />

      {/* ---- Pending Symbols ---- */}
      <span className="flex justify-start whitespace-pre text-left  overflow-hidden w-full   bg-rose-100">
        {pendingSymbols.slice(0, pendingCount).map((symbol, index) => (
          <RegularSymbol
            key={index}
            symbol={getSymbolChar(symbol)}
          />
        ))}
      </span>
    </div>
  );
}

// --- Sub-components & Variants ---

// -------- RegularSymbol --------
const regularSymbolVariants = cva(
  "", // Base classes are handled by variants for clarity.
  {
    variants: {
      symbolType: {
        NONE: "text-gray-600",
        CORRECT: "text-gray-400",
        ERROR: "text-yellow-600",
        ERRORS: "text-rose-700",
        FIXED: "text-rose-900",
      } satisfies Record<FlowLineSymbolType, string>,
    },
    defaultVariants: {
      symbolType: "NONE",
    }
  }
);

type RegularSymbolProps = React.ComponentProps<"span">
  & VariantProps<typeof regularSymbolVariants>
  & { symbol: string; }

function RegularSymbol({ symbolType, symbol, className, ...props }: RegularSymbolProps) {
  return (
    <span className={cn(regularSymbolVariants({ symbolType }), className)} {...props}>
      {symbol}
    </span>
  );
}

// -------- CursorSymbol --------
const cursorSymbolVariants = cva(
  `absolute left-0 -bottom-0 bg-gray-800`,
  {
    variants: {
      cursorType: {
        RECTANGLE: "h-full w-full",
        VERTICAL: "h-full w-1",
        UNDERSCORE: "h-1 w-full",
      } satisfies Record<FlowLineCursorType, string>,
      isTyping: {
        true: "",
        false: "animate-caret-blink",
      },
    },
    defaultVariants: {
      cursorType: "RECTANGLE",
      isTyping: true,
    }
  }
);

type CursorSymbolProps = React.ComponentProps<"span">
  & VariantProps<typeof cursorSymbolVariants>
  & { symbol: string; }

function CursorSymbol({ cursorType, symbol, className, ...props }: CursorSymbolProps) {
  const [isTyping, setIsTyping] = useState(true);
  const blinkDelay = 600;

  // Reset animation when the symbol at the cursor changes.
  useEffect(() => {
    setIsTyping(true);
    const timer = setTimeout(() => {
      setIsTyping(false);
    }, blinkDelay);

    return () => {
      clearTimeout(timer);
    };
  }, [symbol]); // Depend on the symbol prop, not the key.

  return (
    <span className="relative">
      <span className={cn(cursorSymbolVariants({ cursorType, isTyping }), className)} {...props} />
      <span className="text-gray-50 mix-blend-difference">
        {symbol}
      </span>
    </span>
  );
}

// src/components/ui/FlowLine.svelte
<script lang="ts">
  import RegularSymbol from './RegularSymbol.svelte';
  import CursorSymbol from './CursorSymbol.svelte';
  import { getSymbolChar, getSymbolType } from '@/lib/stream-utils';
  import type {
    TypingStream,
    KeyCapPressResult,
    FlowLineCursorType,
    FlowLineCursorMode,
    FlowLineSize,
  } from '@/interfaces/types';

  interface Props {
    stream: TypingStream;
    cursorPosition: number;
    pressResult?: KeyCapPressResult;
    cursorType?: FlowLineCursorType;
    cursorMode?: FlowLineCursorMode;
    size?: FlowLineSize;
    isTyping?: boolean;
    class?: string;
  }

  const {
    stream,
    cursorPosition,
    pressResult = 'NONE',
    cursorType,
    cursorMode = 'HALF',
    size = 'MD',
    isTyping = false,
    class: className = '',
  }: Props = $props();

  const completedCount = 100;
  const pendingCount = 100;

  const startCompleted = $derived(Math.max(0, cursorPosition - completedCount));
  const completedSymbols = $derived(stream.slice(startCompleted, cursorPosition));
  const cursorSymbol = $derived(stream[cursorPosition]);
  const endPending = $derived(cursorPosition + 1 + pendingCount);
  const pendingSymbols = $derived(stream.slice(cursorPosition + 1, endPending));
</script>

<div class="flow-line {size} {cursorMode} {pressResult} {className}">
  <div class="completed-symbols">
    {#each completedSymbols as symbol, i (startCompleted + i)}
      <RegularSymbol symbol={getSymbolChar(symbol)} symbolType={getSymbolType(symbol)} />
    {/each}
  </div>

  <CursorSymbol {cursorType} {isTyping} symbol={cursorSymbol ? getSymbolChar(cursorSymbol) : ''} />

  <div class="pending-symbols">
    {#each pendingSymbols as symbol, i (cursorPosition + 1 + i)}
      <RegularSymbol symbol={getSymbolChar(symbol)} />
    {/each}
  </div>
</div>

<style>
  .flow-line {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100vw;
    font-family: var(--font-mono);
    border: 2px solid var(--color-cursor-border);
  }

  .completed-symbols {
    display: flex;
    justify-content: flex-end;
    white-space: nowrap;
    text-align: right;
    overflow: hidden;
  }

  .pending-symbols {
    display: flex;
    justify-content: flex-start;
    white-space: pre;
    text-align: left;
    overflow: hidden;
  }

  /* Size variants */
  .XS { font-size: 1.25rem; }
  .SM { font-size: 1.5rem; }
  .MD { font-size: 1.875rem; }
  .LG { font-size: 2.25rem; }
  .XL { font-size: 3rem; }

  /* Cursor mode variants */
  .HALF .completed-symbols { width: 50%; }
  .HALF .pending-symbols { width: 50%; }
  .THIRD .completed-symbols { width: 33.333%; }
  .THIRD .pending-symbols { width: 66.666%; }
  .QUARTER .completed-symbols { width: 25%; }
  .QUARTER .pending-symbols { width: 75%; }
  .DINAMIC .completed-symbols { min-width: 8.333%; }
  .DINAMIC .pending-symbols { min-width: 50%; }

  /* Press result variants */
  .NONE { background-color: transparent; }
  .CORRECT { background-color: var(--color-symbol-correct-bg); }
  .ERROR { background-color: var(--color-symbol-error-bg); }
</style>
