// src/components/ui/keycap.tsx
/**
* @file Компонент `KeyCap` для отображения одной физической клавиши.
 * @description Этот компонент является базовым строительным блоком для виртуальной клавиатуры.
 * Он отвечает за визуализацию клавиши, ее символа, маркеров (например, для домашнего ряда)
 * и динамических состояний (видимость, результат нажатия, навигационная роль).
 */
import { cva, type VariantProps } from "class-variance-authority"

import { FingerId, KeyCapColorGroup, KeyCapHomeKeyMarker, KeyCapId, KeyCapLabel, KeyCapNavigationArrow, KeyCapNavigationRole, KeyCapPressResult, KeyCapSymbolSize, KeyCapUnitWidth, Visibility } from "@/interfaces/types";
import { cn } from "@/lib/utils"

/**
 * Варианты стилей для компонента `KeyCap` на основе CVA (Class Variance Authority).
 * Определяет, как клавиша должна выглядеть в зависимости от ее состояния и свойств.
 */
const keyCapVariants = cva(
  `flex items-center justify-center relative rounded-sm h-8
  [&_.keycap-marker]:bg-slate-900`,
  {
    variants: {
      /** Видимость клавиши. */
      visibility: {
        VISIBLE: "visible",
        INVISIBLE: "invisible",
      } satisfies Record<Visibility, string>,

      /** Видимость центральной точки (используется для отладки или специальных маркеров). */
      centerPointVisibility: {
        VISIBLE: "[&_.keycap-center-point]:visible",
        INVISIBLE: "[&_.keycap-center-point]:invisible",
      } satisfies Record<Visibility, string>,

      /** Размер символа на клавише. */
      symbolSize: {
        MD: "[&_.keycap-label]:text-xl",
        SM: "[&_.keycap-label]:text-md",
        XS: "[&_.keycap-label]:text-xs",
      } satisfies Record<KeyCapSymbolSize, string>,

      /** Ширина клавиши в юнитах (1U ~ 19мм). */
      unitWidth: {
        "1U": "w-8",
        "1.25U": "w-11",
        "1.5U": "w-13",
        "1.75U": "w-15",
        "2U": "w-19",
        "2.5U": "w-24",
        "3U": "w-18",
        "5U": "w-38",
      } satisfies Record<KeyCapUnitWidth, string>,

      /** Цветовая группа клавиши. */
      colorGroup: {
        PRIMARY: "",
        SECONDARY: "bg-stone-100 text-stone-400 border-stone-300 outline-stone-300",
        ACCENT: "bg-orange-50 text-orange-400 border-orange-200 outline-orange-300",
      } satisfies Record<KeyCapColorGroup, string>,

      /** Маркер для домашнего ряда (например, черточка или точка). */
      homeKeyMarker: {
        BAR: "",
        DOT: "[&_.keycap-marker]:w-1 [&_.keycap-marker]:h-1",
        NONE: "[&_.keycap-marker]:invisible",
      } satisfies Partial<Record<KeyCapHomeKeyMarker, string>>,



      /** Идентификатор пальца, ответственного за эту клавишу. */
      fingerId: {
        L1: "bg-stone-100/70    border-stone-300   outline-stone-300 ",
        R1: "bg-stone-100/70    border-stone-300   outline-stone-300",
        L2: "bg-amber-100/70    border-amber-300    outline-rose-300   ",
        R2: "bg-amber-100/70   border-amber-300   outline-amber-300  ",
        L3: "bg-sky-100/70     border-sky-300     outline-sky-500    ",
        R3: "bg-sky-100/70     border-sky-300     outline-sky-300    ",
        L4: "bg-indigo-100/70  border-indigo-300  outline-indigo-300 ",
        R4: "bg-indigo-100/70  border-indigo-300  outline-indigo-300 ",
        L5: "bg-purple-100/70  border-purple-300  outline-purple-300 ",
        R5: "bg-purple-100/70  border-purple-300  outline-purple-300 ",

        LB: "",
        RB: "",
      } satisfies Partial<Record<FingerId, string>>,


      /** Стрелка направления движения пальца к клавише. */
      navigationArrow: {
        NONE: '[&_.keycap-path-arrow]:invisible',
        UP: `[&_.keycap-path-arrow]:rotate-0
                [&_.keycap-path-arrow]:-top-1/2
                [&_.keycap-path-arrow]:left-1/2
                [&_.keycap-path-arrow]:-translate-x-1/2`,
        DOWN: `[&_.keycap-path-arrow]:rotate-180
                [&_.keycap-path-arrow]:-bottom-1/2
                [&_.keycap-path-arrow]:left-1/2
                [&_.keycap-path-arrow]:-translate-x-1/2`,
        LEFT: `[&_.keycap-path-arrow]:-rotate-90
                [&_.keycap-path-arrow]:top-1/2
                [&_.keycap-path-arrow]:-left-1/2
                [&_.keycap-path-arrow]:-translate-y-1/2`,
        RIGHT: `[&_.keycap-path-arrow]:rotate-90
                [&_.keycap-path-arrow]:top-1/2
                [&_.keycap-path-arrow]:-right-1/2
                [&_.keycap-path-arrow]:-translate-y-1/2`,
      } satisfies Record<KeyCapNavigationArrow, string>,

      /** Результат нажатия клавиши. */
      pressResult: {
        NONE: "animate-none",
        CORRECT: "animate-bounce",
        ERROR: "bg-red-400 text-red-700",
      } satisfies Record<KeyCapPressResult, string>,

      /** Флаг, указывающий, является ли клавиша частью домашнего ряда. */
      isHomeKey: {
        true: "ring-2",
        false: "ring-0",
      },
      /** Навигационная роль клавиши по движению к целевой клавише. */
      navigationRole: {
        NONE: "text-sky-900 border font-extralight",
        PATH: "ring-4 ring-sky-900 text-sky-900 font-bold",
        TARGET: "ring-4 ring-sky-950/70 text-sky-50  bg-sky-950/70 font-black",
      } satisfies Record<KeyCapNavigationRole, string>,
    },
    compoundVariants: [
      {
        visibility: "INVISIBLE",
        centerPointVisibility: "VISIBLE",
        class: "[&_.keycap-center-point]:invisible",
      },
    ],

    defaultVariants: {
      visibility: "VISIBLE",
      centerPointVisibility: "INVISIBLE",
      navigationRole: "NONE",
      unitWidth: "1U",
      symbolSize: "MD",
      colorGroup: "PRIMARY",
      pressResult: "NONE",
      homeKeyMarker: "NONE",
      navigationArrow: "NONE",
      isHomeKey: false,
    },
  });

/** Пропсы для компонента `KeyCap`. */
export type KeyCapProps = React.ComponentProps<"div">
  & VariantProps<typeof keyCapVariants>
  & KeyCapLabel
  & { keyCapId: KeyCapId };

/**
 * Компонент `KeyCap` отображает одну клавишу виртуальной клавиатуры.
 * @param props Пропсы компонента.
 * @param props.visibility - Определяет видимость клавиши.
 * @param props.centerPointVisibility - Определяет видимость центральной точки.
 * @param props.navigationRole - Определяет навигационную роль клавиши.
 * @param props.navigationArrow - Определяет направление стрелки для движения пальца к целевой клавише..
 * @param props.unitWidth - Определяет ширину клавиши.
 * @param props.colorGroup - Определяет цветовую группу клавиши.
 * @param props.pressResult - Определяет результат нажатия клавиши.
 * @param props.symbolSize - Определяет размер символа на клавише.
 * @param props.homeKeyMarker - Определяет тип маркера домашнего ряда.
 * @param props.isHomeKey - Флаг, указывающий, является ли клавиша домашней.
 * @param props.fingerId - Идентификатор пальца, связанного с клавишей.
 * @param props.symbol - Символ, отображаемый на клавише.
 * @param props.keyCapId - Уникальный идентификатор клавиши.
 *
 * @architectural_notes
 * - **data-keycap-id**: Этот атрибут добавляется в DOM для уникальной идентификации
 *   каждой клавиши. Он используется для поиска конкретной клавиши (например,
 *   домашней клавиши пальца) в логике позиционирования других компонентов.
 * - **keycap-center-point**: Этот невидимый `div` в центре клавиши служит "якорем"
 *   для выравнивания. Его координаты считываются для точного совмещения
 *   клавиатурного кластера с соответствующим пальцем в компоненте `HandsExt`.
 *
 * @returns Элемент JSX, представляющий клавишу.
 */
export function KeyCap({
  visibility,
  centerPointVisibility,
  navigationRole,
  navigationArrow: navigationArrow,
  unitWidth,
  colorGroup,
  pressResult,
  symbolSize,
  homeKeyMarker,
  isHomeKey,
  fingerId,
  symbol = "A",
  keyCapId,
  ...props
}: KeyCapProps) {
  return (
    <div
      data-keycap-id={keyCapId}
      className={cn(
        keyCapVariants({
          visibility,
          centerPointVisibility,
          homeKeyMarker,
          isHomeKey,
          fingerId,
          navigationRole,
          navigationArrow: navigationArrow,
          unitWidth,
          symbolSize,
          colorGroup,
          pressResult
        })
      )}
      {...props}
    >
      {/* ------- LABEL  --------- */}
      <span className="keycap-label">
        {symbol}
      </span>

      {/* ------- MARKER --------- */}
      <div
        className="keycap-marker absolute bottom-0.5 w-3 h-0.5 rounded-full"
      />

      {/* ------- CENTER --------- */}
      <div
        className="keycap-center-point absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2
          w-0.5 h-0.5 rounded-full bg-red-400"
      />

      {/* ------- ARROW --------- */}
      <div className='keycap-path-arrow absolute z-10'>

        <svg width="26" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
          <mask id="path-1-inside-1_119_57" fill="white">
            <path fillRule="evenodd" clipRule="evenodd" d="M27 21L13.5 0L0 21H5.70578V28H20.9231V21H27Z" />
          </mask>
          <path fillRule="evenodd" clipRule="evenodd" d="M27 21L13.5 0L0 21H5.70578V28H20.9231V21H27Z" fill="#27AE60" fillOpacity="0.7" />
          <path fillRule="evenodd" clipRule="evenodd" d="M27 21L13.5 0L0 21H5.70578V28H20.9231V21H27Z" fill="url(#paint0_linear_119_57)" fillOpacity="0.8" />
          <path d="M13.5 0L14.3412 -0.540758L13.5 -1.84926L12.6588 -0.540758L13.5 0ZM27 21V22H28.8317L27.8412 20.4592L27 21ZM0 21L-0.841178 20.4592L-1.83167 22H0V21ZM5.70578 21H6.70578V20H5.70578V21ZM5.70578 28H4.70578V29H5.70578V28ZM20.9231 28V29H21.9231V28H20.9231ZM20.9231 21V20H19.9231V21H20.9231ZM12.6588 0.540758L26.1588 21.5408L27.8412 20.4592L14.3412 -0.540758L12.6588 0.540758ZM0.841178 21.5408L14.3412 0.540758L12.6588 -0.540758L-0.841178 20.4592L0.841178 21.5408ZM5.70578 20H0V22H5.70578V20ZM6.70578 28V21H4.70578V28H6.70578ZM20.9231 27H5.70578V29H20.9231V27ZM19.9231 21V28H21.9231V21H19.9231ZM27 20H20.9231V22H27V20Z" fill="#2A9852" fillOpacity="0.2" mask="url(#path-1-inside-1_119_57)" />
          <defs>
            <linearGradient id="paint0_linear_119_57" x1="13.5" y1="0" x2="13.5" y2="28" gradientUnits="userSpaceOnUse">
              <stop stopColor="#24FF00" />
              <stop offset="1" stopColor="white" stopOpacity="0" />
            </linearGradient>
          </defs>
        </svg>
      </div>
    </div>
  )
}

// src/components/ui/KeyCap.svelte
<script lang="ts">
  import type {
    KeyCapColorGroup,
    KeyCapHomeKeyMarker,
    KeyCapNavigationArrow,
    KeyCapNavigationRole,
    KeyCapSymbolSize,
    KeyCapUnitWidth,
  } from '$interfaces/types';

  interface Props {
    symbol: string;
    keyCapId?: string;
    pressResult?: 'NONE' | 'CORRECT' | 'ERROR';
    visibility?: 'VISIBLE' | 'INVISIBLE';
    isActive?: boolean;
    isHomeKey?: boolean;
    fingerId?: string;
    unitWidth?: KeyCapUnitWidth;
    symbolSize?: KeyCapSymbolSize;
    colorGroup?: KeyCapColorGroup;
    homeKeyMarker?: KeyCapHomeKeyMarker;
    navigationRole?: KeyCapNavigationRole;
    navigationArrow?: KeyCapNavigationArrow;
  }

  let {
    symbol,
    keyCapId,
    pressResult = 'NONE',
    visibility = 'VISIBLE',
    isActive = false,
    isHomeKey = false,
    fingerId,
    unitWidth = '1U',
    symbolSize = 'MD',
    colorGroup = 'PRIMARY',
    homeKeyMarker = 'NONE',
    navigationRole = 'NONE',
    navigationArrow = 'NONE',
  }: Props = $props();

  let unitMultiplier = $derived(parseFloat(unitWidth));

  const uid = $props.id();
  const gradientId = `keycap-arrow-grad-${uid}`;
  const maskId = `keycap-arrow-mask-${uid}`;
</script>

<div
  class="keycap size-{symbolSize} color-{colorGroup} marker-{homeKeyMarker}"
  class:CORRECT={pressResult === 'CORRECT'}
  class:ERROR={pressResult === 'ERROR'}
  class:active={isActive}
  class:home={isHomeKey}
  class:INVISIBLE={visibility === 'INVISIBLE'}
  class:role-target={navigationRole === 'TARGET'}
  class:role-path={navigationRole === 'PATH'}
  data-finger-id={fingerId}
  data-keycap-id={keyCapId}
  data-navigation-role={navigationRole}
  data-navigation-arrow={navigationArrow}
  style:--unit-multiplier={unitMultiplier}
>
  <span class="keycap-label">{symbol}</span>

  <div class="keycap-marker"></div>

  {#if navigationArrow !== 'NONE'}
    <span class="nav-arrow {navigationArrow}" aria-hidden="true">
      <svg width="26" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
        <mask id={maskId} fill="white">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M27 21L13.5 0L0 21H5.70578V28H20.9231V21H27Z" />
        </mask>
        <path fill-rule="evenodd" clip-rule="evenodd" d="M27 21L13.5 0L0 21H5.70578V28H20.9231V21H27Z" fill="#27AE60" fill-opacity="0.7" />
        <path fill-rule="evenodd" clip-rule="evenodd" d="M27 21L13.5 0L0 21H5.70578V28H20.9231V21H27Z" fill="url(#{gradientId})" fill-opacity="0.8" />
        <path d="M13.5 0L14.3412 -0.540758L13.5 -1.84926L12.6588 -0.540758L13.5 0ZM27 21V22H28.8317L27.8412 20.4592L27 21ZM0 21L-0.841178 20.4592L-1.83167 22H0V21ZM5.70578 21H6.70578V20H5.70578V21ZM5.70578 28H4.70578V29H5.70578V28ZM20.9231 28V29H21.9231V28H20.9231ZM20.9231 21V20H19.9231V21H20.9231ZM12.6588 0.540758L26.1588 21.5408L27.8412 20.4592L14.3412 -0.540758L12.6588 0.540758ZM0.841178 21.5408L14.3412 0.540758L12.6588 -0.540758L-0.841178 20.4592L0.841178 21.5408ZM5.70578 20H0V22H5.70578V20ZM6.70578 28V21H4.70578V28H6.70578ZM20.9231 27H5.70578V29H20.9231V27ZM19.9231 21V28H21.9231V21H19.9231ZM27 20H20.9231V22H27V20Z" fill="#2A9852" fill-opacity="0.2" mask="url(#{maskId})" />
        <defs>
          <linearGradient id={gradientId} x1="13.5" y1="0" x2="13.5" y2="28" gradientUnits="userSpaceOnUse">
            <stop stop-color="#24FF00" />
            <stop offset="1" stop-color="white" stop-opacity="0" />
          </linearGradient>
        </defs>
      </svg>
    </span>
  {/if}

  <!-- Center point anchor used by HandsExt positioning logic -->
  <div class="keycap-center-point"></div>
</div>

<style>
  .keycap {
    --keycap-unit: 36px;
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;
    flex-shrink: 0;
    box-sizing: border-box;
    border-radius: var(--radius-sm);
    height: 32px;
    width: calc(var(--keycap-unit) * var(--unit-multiplier, 1));
    padding: 0 var(--spacing-2);
    background-color: transparent;
    border: 1px solid transparent;
    color: #0c4a6e;
    font-weight: 200;
    user-select: none;
  }

  .keycap.INVISIBLE {
    visibility: hidden;
  }

  /* --- Symbol size --- */
  .size-MD .keycap-label { font-size: 13px; }
  .size-SM .keycap-label { font-size: 11px; }
  .size-XS .keycap-label { font-size: 9px; }

  /* --- Color group --- */
  .color-SECONDARY {
    background-color: #f5f5f4;
    color: #a8a29c;
    border-color: #d6d3d1;
  }

  .color-ACCENT {
    background-color: #fff7ed;
    color: #fb923c;
    border-color: #fed7aa;
  }

  /* --- Per-finger color --- */
  .keycap[data-finger-id="L1"],
  .keycap[data-finger-id="R1"] {
    background-color: rgba(245, 245, 244, 0.7);
    border-color: #d6d3d1;
  }
  .keycap[data-finger-id="L2"],
  .keycap[data-finger-id="R2"] {
    background-color: rgba(254, 243, 199, 0.7);
    border-color: #fcd34d;
  }
  .keycap[data-finger-id="L3"],
  .keycap[data-finger-id="R3"] {
    background-color: rgba(224, 242, 254, 0.7);
    border-color: #7dd3fc;
  }
  .keycap[data-finger-id="L4"],
  .keycap[data-finger-id="R4"] {
    background-color: rgba(224, 231, 255, 0.7);
    border-color: #a5b4fc;
  }
  .keycap[data-finger-id="L5"],
  .keycap[data-finger-id="R5"] {
    background-color: rgba(243, 232, 255, 0.7);
    border-color: #d8b4fe;
  }

  /* --- Home key ring --- */
  .keycap.home {
    box-shadow: 0 0 0 2px #0c4a6e;
  }

  /* --- Navigation role (overridden by press result below) --- */
  .keycap.role-path {
    box-shadow: 0 0 0 4px #0c4a6e;
    font-weight: 700;
  }

  .keycap.role-target {
    background-color: rgba(8, 47, 73, 0.7);
    color: #f0f9ff;
    box-shadow: 0 0 0 4px rgba(8, 47, 73, 0.7);
    font-weight: 900;
  }

  /* --- Press result (takes precedence over navigation role) --- */
  .keycap.CORRECT {
    background-color: rgba(22, 101, 52, 0.8);
    color: #f0fdfa;
    border-color: #22c55e;
    font-weight: 800;
  }

  .keycap.ERROR {
    background-color: rgba(239, 68, 68, 0.8);
    color: #fef2f2;
    border-color: #f87171;
    font-weight: 800;
  }

  .keycap.active,
  .keycap:active {
    transform: translateY(1px);
  }

  /* --- Home key marker --- */
  .keycap-marker {
    position: absolute;
    bottom: 2px;
    left: 50%;
    transform: translateX(-50%);
    background-color: #0f172a;
    border-radius: 9999px;
  }

  .marker-BAR .keycap-marker {
    width: 12px;
    height: 2px;
  }

  .marker-DOT .keycap-marker {
    width: 4px;
    height: 4px;
  }

  .marker-NONE .keycap-marker {
    visibility: hidden;
  }

  /* --- Navigation arrow --- */
  .nav-arrow {
    position: absolute;
    line-height: 0;
    pointer-events: none;
    z-index: 10;
  }

  .nav-arrow.UP {
    top: -50%;
    left: 50%;
    transform: translateX(-50%) rotate(0deg);
  }

  .nav-arrow.DOWN {
    bottom: -50%;
    left: 50%;
    transform: translateX(-50%) rotate(180deg);
  }

  .nav-arrow.LEFT {
    top: 50%;
    left: -50%;
    transform: translateY(-50%) rotate(-90deg);
  }

  .nav-arrow.RIGHT {
    top: 50%;
    right: -50%;
    transform: translateY(-50%) rotate(90deg);
  }

  .keycap-center-point {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 2px;
    height: 2px;
    pointer-events: none;
  }
</style>
