// src/components/ui/LessonStatsDisplay.svelte
<script lang="ts">
  import type { TypingStream } from '$interfaces/types';
  import { calculateLessonStats } from '$lib/stats-calculator';

  interface Props {
    stream: TypingStream;
    dictionary: {
      stats_card: {
        title: string;
        cpm: string;
        wpm: string;
        accuracy: string;
        duration: string;
        units: {
          cpm: string;
          wpm: string;
          accuracy: string;
          duration: string;
        };
      };
    };
  }

  const { stream, dictionary }: Props = $props();

  const stats = $derived(calculateLessonStats(stream));

  const stats_card = $derived(dictionary.stats_card);
</script>

{#if stream.length > 0 && stream.some((s) => s.attempts.length > 0)}
  <div class="stats-display">
    <h2 class="title">{stats_card.title}</h2>
    <div class="grid">
      <div class="stat-item">
        <p class="stat-label">{stats_card.cpm}</p>
        <p class="stat-value">{stats.cpm}<span class="stat-unit">{stats_card.units.cpm}</span></p>
      </div>
      <div class="stat-item">
        <p class="stat-label">{stats_card.wpm}</p>
        <p class="stat-value">{stats.wpm}<span class="stat-unit">{stats_card.units.wpm}</span></p>
      </div>
      <div class="stat-item">
        <p class="stat-label">{stats_card.accuracy}</p>
        <p class="stat-value">{stats.accuracy}<span class="stat-unit">{stats_card.units.accuracy}</span></p>
      </div>
      <div class="stat-item">
        <p class="stat-label">{stats_card.duration}</p>
        <p class="stat-value">{stats.durationInSeconds}<span class="stat-unit">{stats_card.units.duration}</span></p>
      </div>
    </div>
  </div>
{/if}

<style>
  .stats-display {
    width: 100%;
    max-width: 640px;
    padding: var(--spacing-6);
    background-color: var(--color-surface);
    border-radius: var(--radius-lg);
    border: 1px solid var(--color-border);
  }

  .title {
    font-size: 1.25rem;
    font-weight: 700;
    margin-bottom: var(--spacing-4);
  }

  .grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: var(--spacing-4);
  }

  @media (min-width: 768px) {
    .grid {
      grid-template-columns: repeat(4, 1fr);
    }
  }

  .stat-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: var(--spacing-4);
    background-color: var(--color-bg);
    border-radius: var(--radius-md);
  }

  .stat-label {
    font-size: 0.875rem;
    color: var(--color-text-muted);
  }

  .stat-value {
    font-size: 1.5rem;
    font-weight: 700;
    color: var(--color-text-primary);
  }

  .stat-unit {
    font-size: 1rem;
    font-weight: 500;
    color: var(--color-text-secondary);
    margin-left: var(--spacing-1);
  }
</style>

// src/components/ui/lesson-stats-display.tsx
import React from 'react';
import { Dictionary, TypingStream } from '@/interfaces/types';
import { calculateLessonStats } from '@/lib/stats-calculator';

interface LessonStatsDisplayProps {
  stream: TypingStream;
  dictionary: Dictionary;
}

const StatItem = ({ label, value, unit }: { label: string; value: string | number; unit?: string }) => (
  <div className="flex flex-col items-center justify-center p-4 bg-slate-100 dark:bg-slate-800 rounded-lg">
    <p className="text-sm text-slate-500 dark:text-slate-400">{label}</p>
    <p className="text-2xl font-bold text-slate-900 dark:text-slate-100">
      {value}
      {unit && <span className="text-lg font-medium text-slate-600 dark:text-slate-300 ml-1">{unit}</span>}
    </p>
  </div>
);

export const LessonStatsDisplay: React.FC<LessonStatsDisplayProps> = ({ stream, dictionary }) => {
  // Do not render anything if the stream is empty or not yet populated
  if (!stream || stream.length === 0 || stream.every((s) => s.attempts.length === 0)) {
    return null;
  }

  const stats = calculateLessonStats(stream);
  const { stats_card } = dictionary;

  return (
    <div className="w-full max-w-2xl mx-auto p-4 bg-white dark:bg-slate-900 rounded-xl shadow-md border border-slate-200 dark:border-slate-700">
      <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">{stats_card.title}</h2>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatItem label={stats_card.cpm} value={stats.cpm} unit={stats_card.units.cpm} />
        <StatItem label={stats_card.wpm} value={stats.wpm} unit={stats_card.units.wpm} />
        <StatItem label={stats_card.accuracy} value={stats.accuracy} unit={stats_card.units.accuracy} />
        <StatItem label={stats_card.duration} value={stats.durationInSeconds} unit={stats_card.units.duration} />
      </div>
    </div>
  );
};
