// src/components/ui/training-scene.tsx
/**
 * @file Компонент `TrainingScene` для отображения основной сцены тренировки.
 * @description Этот компонент является контейнером, который управляет состоянием
 * тренировки с помощью XState-актора и отображает основные UI-элементы:
 * `FlowLine`, `HandsExt` и кнопки управления тренировкой.
 */
import { useSelector } from "@xstate/react";
import type { ActorRefFrom } from "xstate";

import { FingerLayout, HandsSceneViewModel, KeyboardLayout } from "@/interfaces/types";
import { createKeyCoordinateMap, KeyCoordinateMap } from '@/lib/layout-utils';
import { AdjacencyList, createKeyboardGraph } from '@/lib/pathfinding';
import { generateHandsSceneViewModel } from "@/lib/viewModel-builder";
import { getPressResult } from "@/lib/press-result-utils";
import { trainingMachine } from "@/machines/training.machine";
import { getSymbolLayout } from "@/data/layouts";

import { FlowLine } from "./flow-line";
import { HandsExt } from "./hands-ext";
import { DebugState } from "./debug-state";

/** Пропсы для компонента `TrainingScene`. */
type TrainingSceneProps = {
  /** Актор (живой экземпляр) запущенной `trainingMachine`. */
  trainingActor: ActorRefFrom<typeof trainingMachine>;
  /** The layout defining which finger presses which key. */
  fingerLayout: FingerLayout;
  /** The physical layout of the keyboard. */
  keyboardLayout: KeyboardLayout;
};

/**
 * Компонент `TrainingScene` отрисовывает основную сцену тренировки слепой печати.
 * Он подключается к XState-машине `trainingMachine` для получения состояния
 * и отправки событий, а также отображает `FlowLine`, `HandsExt` и элементы управления.
 * @param props Пропсы компонента.
 * @param props.trainingActor Актор `trainingMachine`.
 * @returns Элемент JSX, представляющий тренировочную сцену.
 */
export const TrainingScene = ({ trainingActor, fingerLayout, keyboardLayout }: TrainingSceneProps) => {
  const trainingState = useSelector(trainingActor, (snapshot) => snapshot);
  const { stream, currentIndex, keyboardLayout: keyboardLayoutPreference } = trainingState.context;

  const keyboardGraph: AdjacencyList = createKeyboardGraph(keyboardLayout);
  const keyCoordinateMap: KeyCoordinateMap = createKeyCoordinateMap(keyboardLayout);
  const symbolLayout = getSymbolLayout(keyboardLayoutPreference);

  // Генерируем ViewModel для HandsExt на основе текущего состояния машины
  const viewModel: HandsSceneViewModel = generateHandsSceneViewModel(trainingState.context.stream?.[trainingState.context.currentIndex], fingerLayout, keyboardGraph, keyCoordinateMap);

  const pressResult = getPressResult(trainingState.context.stream?.[trainingState.context.currentIndex]);
  const flowLineFixture = stream[currentIndex];


  return (
    <div className="flex flex-col items-center gap-8">
      <h2 className="text-2xl font-semibold">Training In Progress</h2>
      <p>
        Training Machine State: <code className="font-mono bg-gray-200 dark:bg-gray-800 p-1 rounded">{trainingState.value.toString()}</code>
      </p>

      <FlowLine stream={stream} cursorPosition={currentIndex} pressResult={pressResult} />

      <HandsExt viewModel={viewModel} fingerLayout={fingerLayout} keyboardLayout={keyboardLayout} symbolLayout={symbolLayout}/>

      <div className="w-full max-w-4xl">
        <DebugState dataFlowLine={flowLineFixture} dataViewModel={viewModel} />
      </div>
    </div>
  );
};

// src/components/ui/TrainingScene.svelte
<script lang="ts">
  import type { Actor } from 'xstate';
  import type { trainingMachine } from '@/machines/training.machine';
  import type { Dictionary, FingerLayout, PhysicalLayout } from '@/interfaces/types';

  import { createKeyboardGraph } from '@/lib/pathfinding';
  import { createKeyCoordinateMap } from '@/lib/layout-utils';
  import { generateHandsSceneViewModel } from '@/lib/viewModel-builder';
  import { getPressResult } from '@/lib/press-result-utils';
  import { getSymbolLayout } from '@/data/layouts/layouts';

  import FlowLine from './FlowLine.svelte';
  import HandsExt from './HandsExt.svelte';

  interface Props {
    trainingActor: Actor<typeof trainingMachine>;
    fingerLayout: FingerLayout;
    physicalLayout: PhysicalLayout;
    dictionary: Dictionary;
  }

  const { trainingActor, fingerLayout, physicalLayout, dictionary }: Props = $props();

  // svelte-ignore state_referenced_locally
  let trainingState = $state(trainingActor.getSnapshot());

  $effect(() => {
    trainingState = trainingActor.getSnapshot();
    const sub = trainingActor.subscribe((s) => {
      trainingState = s;
    });
    return () => sub.unsubscribe();
  });

  const stream = $derived(trainingState.context.stream);
  const currentIndex = $derived(trainingState.context.currentIndex);
  const currentSymbolLayoutId = $derived(trainingState.context.currentSymbolLayoutId);

  const keyboardGraph = $derived(createKeyboardGraph(physicalLayout));
  const keyCoordinateMap = $derived(createKeyCoordinateMap(physicalLayout));
  const symbolLayout = $derived(getSymbolLayout(currentSymbolLayoutId));

  // Может быть undefined на одном кадре между завершающим correct-attempt
  // (assign currentIndex++) и переходом trainingMachine в lessonComplete.
  // Оба потребителя принимают undefined: generateHandsSceneViewModel → idle scene,
  // getPressResult → 'NONE'.
  const currentSymbol = $derived(stream[currentIndex]);

  const viewModel = $derived(
    generateHandsSceneViewModel(currentSymbol, fingerLayout, keyboardGraph, keyCoordinateMap)
  );
  const pressResult = $derived(getPressResult(currentSymbol));
</script>

<div class="training-scene">
  <h2 class="title">{dictionary.app.training_in_progress}</h2>
  <p>
    {dictionary.app.training_machine_state}
    <code class="state-code">{trainingState.value.toString()}</code>
  </p>

  <FlowLine
    {stream}
    cursorPosition={currentIndex}
    {pressResult}
    isTyping={!trainingState.matches('lessonComplete')}
  />

  <HandsExt {viewModel} {fingerLayout} {physicalLayout} {symbolLayout} />
</div>

<style>
  .training-scene {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--spacing-6);
    width: 100%;
  }

  .title {
    font-size: 1.5rem;
    font-weight: 700;
  }

  .state-code {
    font-family: var(--font-mono);
    background-color: var(--color-surface);
    padding: var(--spacing-1) var(--spacing-2);
    border-radius: var(--radius-sm);
  }
</style>
