// src/components/ui/user-preferences-page.tsx
// src/components/ui/user-preferences-page.tsx
'use client';

import { useRouter } from 'next/navigation';
import { useUserPreferencesStore } from '@/store/user-preferences.store';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { UserPreferences } from '@/interfaces/user-preferences';
import { Dictionary } from '@/interfaces/types';

interface UserPreferencesPageProps {
  onBack: () => void;
  dictionary: Dictionary;
}

export function UserPreferencesPage({ onBack, dictionary }: UserPreferencesPageProps) {
  const { language, keyboardLayout, updateUserPreferences } = useUserPreferencesStore();
  const router = useRouter();

  const handleLanguageChange = (value: UserPreferences['language']) => {
    updateUserPreferences({ language: value });
    router.refresh();
  };

  const handleKeyboardLayoutChange = (value: UserPreferences['keyboardLayout']) => {
    updateUserPreferences({ keyboardLayout: value });
  };

  return (
    <div className="container mx-auto p-4 max-w-md">
      <h1 className="text-3xl font-bold mb-6">{dictionary.user_preferences.title}</h1>

      <div className="mb-4">
        <label htmlFor="language-select" className="block text-sm font-medium text-gray-700 mb-1">
          {dictionary.user_preferences.language_label}
        </label>
        <Select
          value={language}
          onValueChange={handleLanguageChange}
        >
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder={dictionary.user_preferences.language_placeholder} />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="en">{dictionary.options.languages.en}</SelectItem>
            <SelectItem value="ru">{dictionary.options.languages.ru}</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div className="mb-4">
        <label htmlFor="keyboard-layout-select" className="block text-sm font-medium text-gray-700 mb-1">
          {dictionary.user_preferences.keyboard_layout_label}
        </label>
        <Select
          value={keyboardLayout}
          onValueChange={handleKeyboardLayoutChange}
        >
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder={dictionary.user_preferences.keyboard_layout_placeholder} />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="qwerty">{dictionary.options.layouts.qwerty}</SelectItem>
            <SelectItem value="йцукен">{dictionary.options.layouts.йцукен}</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <button onClick={onBack} className="p-2 mt-4 bg-red-500 text-white rounded">
        {dictionary.user_preferences.back_button}
      </button>
    </div>
  );
}

// src/components/ui/UserPreferencesPage.svelte
<script lang="ts">
  import { preferences, updatePreferences } from '$lib/preferences';
  import Select from './Select.svelte';
  import type { UserPreferences } from '$interfaces/user-preferences';

  interface Props {
    onBack: () => void;
    dictionary: {
      user_preferences: {
        title: string;
        language_label: string;
        keyboard_layout_label: string;
        back_button: string;
      };
    };
  }

  const { onBack, dictionary }: Props = $props();

  const languages: { value: UserPreferences['language']; label: string }[] = [
    { value: 'en', label: 'English' },
    { value: 'ru', label: 'Русский' },
  ];

  const layouts: { value: UserPreferences['keyboardLayout']; label: string }[] = [
    { value: 'qwerty', label: 'QWERTY' },
    { value: 'йцукен', label: 'ЙЦУКЕН' },
  ];
</script>

<div class="preferences-page">
  <h2>{dictionary.user_preferences.title}</h2>

  <label class="field">
    <span class="label-text">{dictionary.user_preferences.language_label}</span>
    <Select
      value={$preferences.language}
      options={languages}
      onChange={(v) => updatePreferences({ language: v as UserPreferences['language'] })}
    />
  </label>

  <label class="field">
    <span class="label-text">{dictionary.user_preferences.keyboard_layout_label}</span>
    <Select
      value={$preferences.keyboardLayout}
      options={layouts}
      onChange={(v) => updatePreferences({ keyboardLayout: v as UserPreferences['keyboardLayout'] })}
    />
  </label>

  <button type="button" class="btn" onclick={onBack}>
    {dictionary.user_preferences.back_button}
  </button>
</div>

<style>
  .preferences-page {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-6);
    max-width: 400px;
    width: 100%;
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-2);
  }

  .label-text {
    font-size: 0.875rem;
    color: var(--color-text-secondary);
  }

  .btn {
    margin-top: var(--spacing-4);
    padding: var(--spacing-2) var(--spacing-4);
    border-radius: var(--radius-md);
    border: 1px solid var(--color-border);
    background-color: var(--color-surface);
    color: var(--color-text-primary);
    cursor: pointer;
    align-self: flex-start;
  }

  .btn:hover {
    background-color: var(--color-surface-hover);
  }
</style>
