// src/components/ui/virtual-keyboard.tsx
import { VirtualKey, FingerId, KeyCapNavigationRole, Visibility } from "@/interfaces/types";
import { KeyCap } from "./keycap";
import { JSX } from "react";
import { KeyCapId } from "@/interfaces/key-cap-id";
import { fingerLayoutASDF } from "@/data/finger-layout-asdf";
import { getFingerByKeyCap } from "@/lib/symbol-utils";
import { getKeyCapIdsByFingerId } from "@/lib/hand-utils";

export type VirtualKeyboardProps = React.ComponentProps<"div">
  & {
    virtualLayout: VirtualKey[][];
    targetKeyCapId?: KeyCapId;
  }

type VirtualRowProps = React.ComponentProps<"div">
  & {
    row: VirtualKey[];
    targetKeyCapId?: KeyCapId;
    activeFingerKeyCapIds: KeyCapId[];
  }

export function VirtualKeyboard({ virtualLayout, targetKeyCapId }: VirtualKeyboardProps): JSX.Element {
  let activeFingerKeyCapIds: KeyCapId[] = [];

  if (targetKeyCapId) {
    const targetFingerId: FingerId | undefined = getFingerByKeyCap(targetKeyCapId, fingerLayoutASDF);
    if (targetFingerId) {
      activeFingerKeyCapIds = getKeyCapIdsByFingerId(targetFingerId, fingerLayoutASDF);
    }
  }

  const rows = virtualLayout.map((row: VirtualKey[], rowIndex: number) => (
    <VirtualRow
      row={row}
      key={rowIndex}
      targetKeyCapId={targetKeyCapId}
      activeFingerKeyCapIds={activeFingerKeyCapIds}
    />
  ));

  return (
    <div className="flex flex-col w-fit gap-0.5">
      {rows}
    </div>
  )
};

function VirtualRow({ row, targetKeyCapId, activeFingerKeyCapIds }: VirtualRowProps): JSX.Element {
  const keyCaps = row.map((virtualKey) => {
    let navigationRole: KeyCapNavigationRole = "IDLE";
    let visibility: Visibility = "INVISIBLE";

    if (virtualKey.keyCapId === targetKeyCapId) {
      navigationRole = "TARGET";
      visibility = "VISIBLE";
    } else if (activeFingerKeyCapIds.includes(virtualKey.keyCapId)) {
      navigationRole = "IDLE";
      visibility = "VISIBLE";
    }

    return (
      <KeyCap
        key={virtualKey.keyCapId}
        {...virtualKey}
        navigationRole={navigationRole}
        visibility={visibility}
      />
    );
  });

  return (
    <div className="flex flex-nowrap gap-0.5">
      {keyCaps}
    </div>
  );
};

// src/components/ui/VirtualKeyboard.svelte
<script lang="ts">
  import type { KeyboardLayout, SymbolLayout, VirtualLayout } from '$interfaces/types';
  import { getLabel } from '$lib/symbol-utils';
  import KeyCap from './KeyCap.svelte';

  interface Props {
    virtualLayout: VirtualLayout;
    keyboardLayout: KeyboardLayout;
    symbolLayout: SymbolLayout;
  }

  const { virtualLayout, keyboardLayout, symbolLayout }: Props = $props();
</script>

<div class="keyboard">
  {#each virtualLayout as row, rowIndex (rowIndex)}
    <div class="row">
      {#each row as virtualKey (virtualKey.keyCapId)}
        <KeyCap
          keyCapId={virtualKey.keyCapId}
          symbol={getLabel(virtualKey.keyCapId, symbolLayout, keyboardLayout)}
          pressResult={virtualKey.pressResult ?? 'NONE'}
          visibility={virtualKey.visibility ?? 'VISIBLE'}
          fingerId={virtualKey.fingerId}
          unitWidth={virtualKey.unitWidth}
          symbolSize={virtualKey.symbolSize}
          homeKeyMarker={virtualKey.homeKeyMarker}
          isHomeKey={virtualKey.isHomeKey}
          colorGroup={virtualKey.colorGroup}
          navigationRole={virtualKey.navigationRole}
          navigationArrow={virtualKey.navigationArrow}
        />
      {/each}
    </div>
  {/each}
</div>

<style>
  .keyboard {
    display: flex;
    flex-direction: column;
    width: fit-content;
    gap: var(--spacing-2);
    background-color: transparent;
  }

  .row {
    display: flex;
    flex-wrap: nowrap;
    gap: var(--spacing-3);
  }
</style>
